baseURL: "http://mrc-ide.github.io/odin-news/"
languageCode: "en-gb"
title: "Odin News"
theme: "PaperMod"
enableEmoji: true

params:
  # https://github.com/adityatelange/hugo-PaperMod/wiki/Installation#sample-configyml
  DateFormat: "1 January 2006"
  disableThemeToggle: true
  disableSpecial1stPost: true
  hideMeta: false

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
